name: Build Steam Game Achievements

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Generate Steam achievements Markdown
        run: |
          node scripts/build_steam.mjs
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
