name: Build Steam Game Achievements

on:
  workflow_dispatch:
    inputs:
      appid:
        description: 'Steam AppID (p. ej. 409710 para BioShock Remastered)'
        required: true
      title:
        description: "Título que irá dentro del .md (p. ej. 'BioShock Remastered — Logros')"
        required: true
      output:
        description: "Nombre de archivo de salida (.md) en la raíz (p. ej. bioshock_remastered.md)"
        required: true
      xbox_titleid:
        description: "Xbox TitleID DECIMAL (opcional, p. ej. 1096157158)"
        required: false
      merge_mode:
        description: "Cómo combinar: merge (por defecto), steam o xbox"
        required: false
        default: "merge"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install node-fetch@2

      - name: Generate Markdown
        run: |
          node scripts/build_steam.mjs
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          XBL_API_KEY: ${{ secrets.XBL_API_KEY }} # <- añade este secret si quieres fusionar con Xbox
          APPID: ${{ inputs.appid }}
          TITLE: ${{ inputs.title }}
          OUTPUT: ${{ inputs.output }}
          XBOX_TITLEID: ${{ inputs.xbox_titleid }}
          MERGE_MODE: ${{ inputs.merge_mode }}
