name: Build Steam Game Achievements

on:
  workflow_dispatch:
    inputs:
      appid:
        description: "Steam AppID (ej. 409710 para BioShock Remastered)"
        required: true
      title:
        description: "Título que irá dentro del .md (cabecera grande)"
        required: true
      output_md:
        description: "Nombre del archivo .md en la raíz (ej. bioshock_remastered.md)"
        required: true
        default: "game.md"
      xbox_titleid:
        description: "Xbox Title ID (hex, opcional, ej. 15E009DD). Si lo dejas vacío, no se fusiona Xbox."
        required: false
        default: ""
      prefer_icons:
        description: "De dónde preferir iconos al fusionar (steam|xbox)"
        required: false
        default: "steam"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install node-fetch@2

      - name: Generate Steam achievements Markdown
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          APPID: ${{ inputs.appid }}
          TITLE: ${{ inputs.title }}
          OUTPUT: ${{ inputs.output_md }}
        run: node scripts/build_steam.mjs

      # --- Si hay xbox_titleid, bajamos los logros Xbox y los fusionamos ---
      - name: Fetch Xbox achievements JSON (xbl.io)
        if: ${{ inputs.xbox_titleid != '' }}
        env:
          XBL_API_KEY: ${{ secrets.XBL_API_KEY }}
          XBOX_TITLEID: ${{ inputs.xbox_titleid }}
        run: |
          node scripts/fetch_xbox.mjs \
            --titleId="$XBOX_TITLEID" \
            --out="tmp/xbox_${XBOX_TITLEID}.json"

      - name: Merge Xbox Gamerscore + (opcional iconos)
        if: ${{ inputs.xbox_titleid != '' }}
        run: |
          node scripts/merge_xbox_points.mjs \
            --md="${{ inputs.output_md }}" \
            --json="tmp/xbox_${{ inputs.xbox_titleid }}.json" \
            --preferIcons="${{ inputs.prefer_icons }}"

      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build ${{
            inputs.title
          }} achievements (Steam${{ inputs.xbox_titleid != '' && ' + Xbox' || '' }})"
          file_pattern: |
            ${{ inputs.output_md }}
            tmp/**
