name: Build Game Achievements

on:
  workflow_dispatch:
    inputs:
      source_mode:
        description: "Origen: steam | xbox | both"
        required: true
        default: "both"
      appid:
        description: "Steam AppID (si source_mode=steam|both)"
        required: false
      xbox_titleid:
        description: "Xbox Title ID (hex, ej. 15E009DD) si source_mode=xbox|both"
        required: false
      title:
        description: "Título que aparece dentro del .md"
        required: true
      output_md:
        description: "Archivo .md (raíz del repo)"
        required: true
        default: "game.md"
      prefer_icons:
        description: "Iconos preferidos: steam|xbox (sólo en both)"
        required: false
        default: "steam"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install node-fetch@2

      # ============ STEAM ONLY ============
      - name: Build from Steam only
        if: ${{ inputs.source_mode == 'steam' }}
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          APPID: ${{ inputs.appid }}
          TITLE: ${{ inputs.title }}
          OUTPUT: ${{ inputs.output_md }}
        run: |
          node scripts/build_steam.mjs   # genera el MD (ES) y guarda tmp/steam_names_<appid>.json

      # ============ XBOX ONLY ============
      - name: Build from Xbox only
        if: ${{ inputs.source_mode == 'xbox' }}
        env:
          XBL_API_KEY: ${{ secrets.XBL_API_KEY }}
        run: |
          node scripts/build_xbox.mjs \
            --titleId="${{ inputs.xbox_titleid }}" \
            --title="${{ inputs.title }}" \
            --out="${{ inputs.output_md }}"

      # ============ BOTH (Steam + Xbox) ============
      - name: Build Steam base
        if: ${{ inputs.source_mode == 'both' }}
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          APPID: ${{ inputs.appid }}
          TITLE: ${{ inputs.title }}
          OUTPUT: ${{ inputs.output_md }}
        run: |
          node scripts/build_steam.mjs   # genera MD en español + sidecar EN/ES: tmp/steam_names_<appid>.json

      - name: Fetch Xbox achievements JSON
        if: ${{ inputs.source_mode == 'both' }}
        env:
          XBL_API_KEY: ${{ secrets.XBL_API_KEY }}
          XBOX_TITLEID: ${{ inputs.xbox_titleid }}
        run: |
          node scripts/fetch_xbox.mjs \
            --titleId="$XBOX_TITLEID" \
            --out="tmp/xbox_${XBOX_TITLEID}.json"

      - name: Merge Xbox Gamerscore (and optional icons)
        if: ${{ inputs.source_mode == 'both' }}
        run: |
          node scripts/merge_xbox_points.mjs \
            --md="${{ inputs.output_md }}" \
            --json="tmp/xbox_${{ inputs.xbox_titleid }}.json" \
            --steamNames="tmp/steam_names_${{ inputs.appid }}.json" \
            --preferIcons="${{ inputs.prefer_icons }}"

      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build ${{
            inputs.title
          }} achievements (${{ inputs.source_mode }})"
          file_pattern: |
            ${{ inputs.output_md }}
            tmp/**
